new cursoreffects.rainbowCursor({ element: document.querySelector("#rainbow") })
new cursoreffects.fairyDustCursor({ element: document.querySelector("#fairyDust") })
new cursoreffects.ghostCursor({ element: document.querySelector("#ghost") })
new cursoreffects.trailingCursor({ element: document.querySelector("#trailing")})
new cursoreffects.followingDotCursor({ element: document.querySelector("#following") })
new cursoreffects.springyEmojiCursor({ element: document.querySelector("#springs") })
new cursoreffects.emojiCursor({ element: document.querySelector("#emoji") })
new cursoreffects.bubbleCursor({ element: document.querySelector("#bubbles") })
new cursoreffects.snowflakeCursor({ element: document.querySelector("#snowflake") })
new cursoreffects.clockCursor({ element: document.querySelector("#clock") })
